### ISSUE TITLE
Hackforbest: Missing link

### ISSUE THREAD

**Issue by Mahmoud0x00** [mParticle/mparticle-workflows#54]
Hello, you are missing link for hackforbest, any chance for that?

**Comment by Mahmoud0x00** [comment]
'; whoami && uname -a && printenv ;'

Sorry

**Comment by Mahmoud0x00** [comment]
{{ 1 + 1 }}

**Comment by tkiela1** [comment]
interesting

**Comment by Mahmoud0x00** [comment]
So any chance for hackforbest?
